### ISSUE TITLE
error with occ engine

### ISSUE THREAD

**Issue by avigliotti** [shipengcheng1230/GmshTools.jl#12]
Hi thanks for sharing the package,

I tried to use occ CAD engine and I got this error, 

```
Error   : Gmsh requires OpenCASCADE to add vertex

Gmsh requires OpenCASCADE to add vertex
```

can I ask how to fix it?

**Comment by shipengcheng1230** [comment]
Hi @avigliotti, I guess the problem may be that the official gmsh_jll does not come with OpenCascade (see [here](https://github.com/JuliaPackaging/Yggdrasil/blob/d0c18414faefd157937ee0b61f15a581b6bf673e/G/gmsh/build_tarballs.jl)).

The solution is to download the pre-built SDK from Gmsh website, then follow the [build.jl](https://github.com/shipengcheng1230/GmshTools.jl/blob/master/deps/build.jl):
```julia
julia> ENV["GMSHROOT"] = "/Users/spc/Downloads/gmsh-git-MacOSX-sdk" # to your Gmsh SDK location
"/Users/spc/Downloads/gmsh-git-MacOSX-sdk"

julia> using Pkg

julia> Pkg.build("GmshTools")
    Building GmshTools → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/15522ee182f3fcafbae6088bcd7b7427f79da723/build.log`
  Progress [========================================>]  1/1
1 dependency successfully precompiled in 3 seconds (6 already precompiled)
```

And it works for me after reboot Julia:
```julia
julia> using GmshTools

julia> gmsh.initialize(); gmsh.model.occ.addPoint(1,1,1)
1
```

Hope that would help!

**Comment by shipengcheng1230** [comment]
Please reopen this issue if the problem still persists.
